/**
 * buildBundlePullScript() — generates the bash script that Hermes runs
 * at every boot via systemd ExecStartPre. Pulls each per-agent bundle
 * tarball from Storage, extracts to /var/lib/weuseai/bundle/, filters
 * skills by tier, and copies SKILL.md files into Hermes' skill discovery
 * path (/home/weuseai/.hermes/skills/<id>/SKILL.md).
 *
 * Spec: docs/plans/2026-05-08-phase-2e-2-bundle-delivery-spec.md
 * D1 lock 2026-05-12: multi-persona MVP — script loops over
 * WEUSEAI_AGENT_SLUGS (CSV) instead of pulling a single bundle.
 *
 * SLA contract:
 *   - On Storage success: full per-agent bundle installed; tier filter
 *     applied; bundle_pull_attempts row inserted with status='success'.
 *   - On Storage failure (network, 5xx, signed-URL expiry): exit 0
 *     (DON'T fail Hermes boot). Customer keeps minimal bootstrap from
 *     setup-script. bundle_pull_attempts row inserted with appropriate
 *     status. Next boot retries.
 *   - Each persona is pulled INDEPENDENTLY: if web-app-builder fails to
 *     pull, the-pro + doc-expert still install successfully.
 *
 * Idempotent: each boot writes /var/lib/weuseai/bundle/<slug>/.installed-version
 * after a successful install. Subsequent boots compare desired vs
 * installed; skip pull if already at the right version.
 */

export type BundlePullScriptParams = {
  /**
   * Customer's UUID — written to .env at provision time, read by the
   * boot script via `source /home/weuseai/.hermes/.env`.
   */
  customerId: string
  /**
   * Bundle-fetch Edge Function URL. Defaults to production. Tests can
   * override to point at a mock server.
   */
  bundleFetchUrl?: string
  /**
   * Bundle-pull-record Edge Function URL. Defaults to production.
   */
  bundlePullRecordUrl?: string
}

const DEFAULT_BUNDLE_FETCH_URL =
  'https://gtjgsligllbjcisiyrah.supabase.co/functions/v1/bundle-fetch'
const DEFAULT_BUNDLE_PULL_RECORD_URL =
  'https://gtjgsligllbjcisiyrah.supabase.co/functions/v1/bundle-pull-record'

const BUNDLE_DIR_BASE = '/var/lib/weuseai/bundle'
const HERMES_SKILLS_DIR = '/home/weuseai/.hermes/skills'
const PULL_LOG = '/var/log/weuseai-bundle-pull.log'
const FETCH_TIMEOUT_SEC = 30
const DOWNLOAD_TIMEOUT_SEC = 60

/**
 * Generate the bash script. Writes to /usr/local/bin/weuseai-bundle-pull
 * during initial provisioning.
 *
 * `set -u` is on (catch unset env vars), but `set -e` is OFF — we want
 * graceful failure: any error inside the script logs + records telemetry
 * + exits 0 so Hermes can still boot with the minimal bootstrap.
 */
export function buildBundlePullScript(p: BundlePullScriptParams): string {
  const fetchUrl = p.bundleFetchUrl ?? DEFAULT_BUNDLE_FETCH_URL
  const recordUrl = p.bundlePullRecordUrl ?? DEFAULT_BUNDLE_PULL_RECORD_URL

  return `#!/bin/bash
# weuseai-bundle-pull — Phase 2E-2 + D1 multi-persona (2026-05-12).
# Generated by services/provisioning/src/bundle-pull-script.ts.
# Do not edit on the VPS; re-provision to update.
#
# Runs as Hermes systemd ExecStartPre. Pulls each tier-granted persona
# bundle from Storage and installs SKILL.md files into Hermes' discovery
# path. Failure mode per bundle: log + record + continue.

set -u
set -o pipefail

LOG="${PULL_LOG}"
mkdir -p "$(dirname "$LOG")"
touch "$LOG"
chmod 0644 "$LOG"

log() {
  echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*" | tee -a "$LOG"
}

# ─── Read provisioning env ────────────────────────────────────────────
if [ ! -f /home/weuseai/.hermes/.env ]; then
  log "✗ /home/weuseai/.hermes/.env missing; cannot pull bundle"
  exit 0
fi
set -a
source /home/weuseai/.hermes/.env
set +a

CID="\${WEUSEAI_CUSTOMER_ID:-${p.customerId}}"
TIER="\${WEUSEAI_TIER:-starter}"
# Phase 5-3.c: per-customer HMAC instance token, sent to bundle-fetch as
# Authorization: Bearer so the server can verify this VPS owns $CID (security
# finding H2/H3, 2026-06-14). Sourced from .env (written by setup-script as
# HERMES_INSTANCE_TOKEN). Empty on VPSes provisioned before this change — the
# server fails open when its HMAC key is unset, so omission is safe.
INSTANCE_TOKEN="\${HERMES_INSTANCE_TOKEN:-}"

# D1 multi-persona: WEUSEAI_AGENT_SLUGS is the CSV list of personas at
# this customer's tier (e.g. "the-pro,doc-expert,slide-master"). Falls
# back to the legacy single-slug var for back-compat with pre-D1
# .env files (Phase 2E callers).
SLUGS_CSV="\${WEUSEAI_AGENT_SLUGS:-\${WEUSEAI_AGENT_SLUG:-the-pro}}"

if [ -z "$CID" ]; then
  log "✗ Missing WEUSEAI_CUSTOMER_ID in .env"
  exit 0
fi
if [ -z "$SLUGS_CSV" ]; then
  log "✗ Missing WEUSEAI_AGENT_SLUGS in .env"
  exit 0
fi

# Split CSV → bash array. Trim whitespace defensively.
IFS=',' read -r -a SLUGS_ARR <<< "$SLUGS_CSV"
log "Pulling \${#SLUGS_ARR[@]} bundles for cid=$CID tier=$TIER: $SLUGS_CSV"

# ─── Telemetry helper ─────────────────────────────────────────────────
# Called once per persona-bundle attempt.
record_attempt() {
  local slug="$1"
  local status="$2"
  local version_requested="\${3:-}"
  local version_installed="\${4:-}"
  local error_detail="\${5:-}"
  local bytes_pulled="\${6:-}"
  local duration_ms="\${7:-}"

  local payload
  payload=$(cat <<JSON
{
  "customer_id": "$CID",
  "agent_slug": "$slug",
  "version_requested": "$version_requested",
  "version_installed": "$version_installed",
  "status": "$status",
  "error_detail": "$error_detail",
  "bytes_pulled": $\{bytes_pulled:-null\},
  "duration_ms": $\{duration_ms:-null\}
}
JSON
)
  # Best-effort POST. Any failure here is silently swallowed — telemetry
  # write must never propagate to customer-facing chat behavior.
  curl -fsS -X POST "${recordUrl}" \\
    -H "Content-Type: application/json" \\
    -d "$payload" \\
    --max-time 10 \\
    >> "$LOG" 2>&1 || log "⚠ telemetry record failed (non-fatal) for $slug"
}

# ─── Tier filter helper (per-bundle) ──────────────────────────────────
# Reads $slug/$version manifest, decides which skill subdirs to install
# vs skip based on $TIER. Removes "no-longer-allowed" SKILL.md symlinks
# on tier downgrade.
apply_tier_filter() {
  local slug="$1"
  local version="$2"
  local tier="$3"
  local manifest="${BUNDLE_DIR_BASE}/$slug/$version/manifest.json"

  if [ ! -f "$manifest" ]; then
    # A bundle with no manifest.json is a packaging failure, not a benign
    # skip: silently continuing would install a persona shell with ZERO
    # tier-filtered skills (or leave stale ones), so the customer looks
    # provisioned but their skills are missing. Fail the bundle so the
    # caller records it + (when all bundles fail) systemd surfaces it.
    log "✗ manifest.json missing in bundle ($manifest); failing tier filter"
    return 1
  fi

  # No jq dependency: use Python (always available on Ubuntu base images)
  # for the JSON parse + tier filtering decision.
  python3 - "$manifest" "$tier" <<'PYEOF' > /tmp/weuseai-skill-filter.txt
import json, sys
manifest_path, tier = sys.argv[1], sys.argv[2]
with open(manifest_path) as f:
    m = json.load(f)
# v1.4 fix (2026-06-10): WEUSEAI_TIER carries the REAL slug, which since
# the v1.4 restructure can be a canonical feature-bundle slug. Manifest
# enabled_for_tiers values are the legacy spec-class slugs, so resolve the
# canonical slug to its spec-class FIRST — mirrors resolveTierToSpecClass()
# in customer-flow.ts (drift-pinned by tests/bundle-pull-tier-filter.spec.ts).
# Without this, e.g. tier='done-for-you' matched nothing and EVERY skill was
# skipped at install — a customer with persona shells but zero skills.
TIER_SPEC_CLASS = {
    'bare': 'starter', 'solo': 'starter', 'voice-starter': 'starter',
    'done-for-you': 'pro',
    'library-full': 'studio',
}
tier = TIER_SPEC_CLASS.get(tier, tier)
TIER_RANK = { 'starter': 1, 'pro': 2, 'studio': 3 }
def tier_to_efl(t):
    rank = TIER_RANK.get(t, 0)
    return [k for k, v in TIER_RANK.items() if v >= rank]
for skill in m.get('skills', []):
    sid = skill.get('id')
    if not sid:
        continue
    efl = skill.get('enabled_for_tiers')
    if not efl:
        legacy = skill.get('tier')
        if legacy:
            efl = tier_to_efl(legacy)
    if efl and tier in efl:
        print(f'INSTALL\\t{sid}')
    else:
        print(f'SKIP\\t{sid}\\t' + ','.join(efl or []))
PYEOF

  while IFS=$'\\t' read -r action skill_id rest; do
    case "$action" in
      INSTALL)
        local src="${BUNDLE_DIR_BASE}/$slug/$version/skills/$skill_id/SKILL.md"
        local dst="${HERMES_SKILLS_DIR}/$skill_id/SKILL.md"
        if [ -f "$src" ]; then
          mkdir -p "$(dirname "$dst")"
          cp "$src" "$dst"
          chown -R weuseai:weuseai "$(dirname "$dst")"
          log "  ✓ installed $skill_id (from $slug)"
        else
          log "  ⚠ $skill_id manifest entry exists but $src missing"
        fi
        ;;
      SKIP)
        # Remove the symlink/file if present (tier downgrade path).
        rm -f "${HERMES_SKILLS_DIR}/$skill_id/SKILL.md" 2>/dev/null
        log "  ✗ skipped $skill_id (tier=$tier not in [$rest])"
        ;;
    esac
  done < /tmp/weuseai-skill-filter.txt

  rm -f /tmp/weuseai-skill-filter.txt

  # D1 lock: install the persona-shell SKILL.md at top level so Hermes
  # auto-exposes /<slug> as a slash command (R1 verified 2026-05-12).
  # The shell SKILL.md lives at the bundle's <slug>/SKILL.md (NOT
  # inside skills/) and gets copied to ~/.hermes/skills/<slug>/SKILL.md.
  local shell_src="${BUNDLE_DIR_BASE}/$slug/$version/SKILL.md"
  local shell_dst="${HERMES_SKILLS_DIR}/$slug/SKILL.md"
  if [ -f "$shell_src" ]; then
    mkdir -p "$(dirname "$shell_dst")"
    cp "$shell_src" "$shell_dst"
    chown -R weuseai:weuseai "$(dirname "$shell_dst")"
    log "  ✓ persona-shell $slug installed (/<slug> slash command exposed)"
  fi
}

# ─── Safe bundle-fetch request body ───────────────────────────────────
# Build the {customer_id, agent_slug} JSON with python3 json.dumps so a
# special char in $CID/$slug (quote, backslash, control char) can NEVER
# corrupt the request — the previous inline "{\"customer_id\":\"$CID\"...}"
# string-interpolation broke on any such char. Same no-jq convention as
# apply_tier_filter (python3 is always present on the Ubuntu base image).
fetch_body_json() {
  local agent_slug="$1"
  python3 - "$CID" "$agent_slug" <<'PYEOF'
import json, sys
print(json.dumps({"customer_id": sys.argv[1], "agent_slug": sys.argv[2]}))
PYEOF
}

# ─── Pull one bundle ──────────────────────────────────────────────────
# Returns 0 on success, 1 on failure. Loop continues on either result.
pull_bundle() {
  local slug="$1"
  local start_ms
  start_ms=$(date +%s%3N)

  log "▶ Fetching bundle metadata for $slug (cid=$CID, tier=$TIER)"
  local fetch_body
  fetch_body=$(fetch_body_json "$slug")
  local response
  local -a auth_args=()
  if [ -n "$INSTANCE_TOKEN" ]; then
    auth_args=(-H "Authorization: Bearer $INSTANCE_TOKEN")
  fi
  response=$(curl -fsS -X POST "${fetchUrl}" \\
    -H "Content-Type: application/json" \\
    "\${auth_args[@]}" \\
    -d "$fetch_body" \\
    --max-time ${FETCH_TIMEOUT_SEC} 2>>"$LOG") || {
      local duration=$(( $(date +%s%3N) - start_ms ))
      log "  ✗ bundle-fetch failed for $slug; skipping"
      record_attempt "$slug" "storage_unavailable" "" "" "bundle-fetch HTTP failure" "" "$duration"
      return 1
    }

  local version
  version=$(echo "$response" | grep -oE '"version":"[^"]+"' | head -n1 | sed 's/"version":"\\([^"]*\\)"/\\1/')
  local signed_url
  signed_url=$(echo "$response" | grep -oE '"signed_url":"[^"]+"' | head -n1 | sed 's/"signed_url":"\\([^"]*\\)"/\\1/' | sed 's|\\\\/|/|g')

  if [ -z "$version" ] || [ -z "$signed_url" ]; then
    local duration=$(( $(date +%s%3N) - start_ms ))
    log "  ✗ bundle-fetch returned malformed response for $slug: $response"
    record_attempt "$slug" "failed" "" "" "bundle-fetch malformed response" "" "$duration"
    return 1
  fi

  # Idempotency gate
  local installed_file="${BUNDLE_DIR_BASE}/$slug/.installed-version"
  if [ -f "$installed_file" ]; then
    local installed_version
    installed_version=$(cat "$installed_file")
    if [ "$installed_version" = "$version" ]; then
      local duration=$(( $(date +%s%3N) - start_ms ))
      log "  ✓ $slug@$version already installed; re-applying tier filter only"
      if ! apply_tier_filter "$slug" "$version" "$TIER"; then
        log "  ✗ tier filter failed for $slug (manifest missing on installed bundle)"
        record_attempt "$slug" "failed" "$version" "$version" "manifest.json missing" "" "$duration"
        return 1
      fi
      record_attempt "$slug" "success" "$version" "$version" "" "" "$duration"
      return 0
    fi
    log "  installed version $installed_version differs from target $version; pulling fresh"
  fi

  # Download + extract
  local target_dir="${BUNDLE_DIR_BASE}/$slug/$version"
  mkdir -p "$target_dir"

  log "  Downloading $slug@$version..."
  local tmpfile
  tmpfile=$(mktemp /tmp/weuseai-bundle.XXXXXX.tar.gz)

  curl -fsSL "$signed_url" -o "$tmpfile" --max-time ${DOWNLOAD_TIMEOUT_SEC} 2>>"$LOG" || {
    local duration=$(( $(date +%s%3N) - start_ms ))
    log "  ✗ Download failed for $slug"
    record_attempt "$slug" "failed" "$version" "" "download HTTP failure" "" "$duration"
    rm -f "$tmpfile"
    return 1
  }

  local bytes
  bytes=$(stat -c%s "$tmpfile" 2>/dev/null || stat -f%z "$tmpfile" 2>/dev/null || echo 0)
  log "  Downloaded $bytes bytes"

  tar -xzf "$tmpfile" -C "$target_dir" 2>>"$LOG" || {
    local duration=$(( $(date +%s%3N) - start_ms ))
    log "  ✗ Extract failed for $slug"
    record_attempt "$slug" "failed" "$version" "" "tar extract failure" "$bytes" "$duration"
    rm -f "$tmpfile"
    return 1
  }
  rm -f "$tmpfile"

  chown -R weuseai:weuseai "$target_dir"

  if ! apply_tier_filter "$slug" "$version" "$TIER"; then
    local duration=$(( $(date +%s%3N) - start_ms ))
    log "  ✗ tier filter failed for $slug (manifest missing); not marking installed"
    record_attempt "$slug" "failed" "$version" "" "manifest.json missing" "$bytes" "$duration"
    return 1
  fi

  echo "$version" > "$installed_file"

  local duration=$(( $(date +%s%3N) - start_ms ))
  log "  ✓ Bundle install complete: $slug@$version ($bytes bytes, \${duration}ms)"
  record_attempt "$slug" "success" "$version" "$version" "" "$bytes" "$duration"
  return 0
}

# ─── Custom persona pull (Persona Genesis, 2026-06-10) ────────────────
# Best-effort attempt to pull this customer's GENERATED persona bundle
# (slug custom-<cid>). Most customers have none — bundle-fetch answers
# 403/404 and we skip SILENTLY (no telemetry row: an absent custom persona
# is the normal state, not a failure). Real failures (network, 5xx after a
# bundle exists) still surface via pull_bundle's normal telemetry on the
# next call. Tier + ownership are enforced server-side by bundle-fetch —
# this client never decides eligibility.
pull_custom_persona() {
  local slug="custom-$CID"
  local probe_body
  probe_body=$(fetch_body_json "$slug")
  local probe
  probe=$(curl -sS -o /tmp/weuseai-custom-probe.json -w "%{http_code}" -X POST "${fetchUrl}" \\
    -H "Content-Type: application/json" \\
    -d "$probe_body" \\
    --max-time ${FETCH_TIMEOUT_SEC} 2>>"$LOG") || {
      log "  (custom persona probe network-failed; skipping silently)"
      rm -f /tmp/weuseai-custom-probe.json
      return 0
    }
  rm -f /tmp/weuseai-custom-probe.json
  case "$probe" in
    200)
      log "▶ Custom persona found for cid=$CID; pulling $slug"
      if pull_bundle "$slug"; then
        SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
      else
        FAIL_COUNT=$((FAIL_COUNT + 1))
      fi
      ;;
    403|404|400)
      log "  (no custom persona for this customer — normal)"
      ;;
    *)
      log "  ⚠ custom persona probe HTTP $probe; skipping this boot"
      ;;
  esac
}

# ─── Main loop ────────────────────────────────────────────────────────
LOOP_START_MS=$(date +%s%3N)
SUCCESS_COUNT=0
FAIL_COUNT=0

for slug in "\${SLUGS_ARR[@]}"; do
  # Trim whitespace defensively (CSV-edge cases).
  slug="\${slug// /}"
  if [ -z "$slug" ]; then continue; fi

  if pull_bundle "$slug"; then
    SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
  else
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
done

pull_custom_persona

TOTAL_DURATION=$(( $(date +%s%3N) - LOOP_START_MS ))
log "✓ Multi-persona pull complete: $SUCCESS_COUNT success, $FAIL_COUNT fail in \${TOTAL_DURATION}ms"

# Surface a TOTAL failure to systemd (2026-06-14): when we attempted at
# least one bundle and EVERY attempt failed, ExecStartPre must see a
# non-zero exit so the gateway start is held + the failure is visible —
# otherwise the agent boots with zero personas and looks "running" while
# broken. A zero-attempt boot (e.g. persona-free \`bare\` tier) is NOT a
# failure: FAIL_COUNT is 0, so we still exit 0 and let Hermes boot.
if [ "$SUCCESS_COUNT" -eq 0 ] && [ "$FAIL_COUNT" -gt 0 ]; then
  log "✗ All $FAIL_COUNT bundle(s) failed — exiting non-zero so systemd ExecStartPre surfaces it"
  exit 1
fi

exit 0
`
}
