/**
 * buildBundlePullScript() — generates the bash script that Hermes runs
 * at every boot via systemd ExecStartPre. Pulls the per-agent bundle
 * tarball from Storage, extracts to /var/lib/weuseai/bundle/, filters
 * skills by tier, and copies SKILL.md files into Hermes' skill discovery
 * path (/home/weuseai/.hermes/skills/<id>/SKILL.md).
 *
 * Spec: docs/plans/2026-05-08-phase-2e-2-bundle-delivery-spec.md
 *
 * SLA contract:
 *   - On Storage success: full per-agent bundle installed; tier filter
 *     applied; bundle_pull_attempts row inserted with status='success'.
 *   - On Storage failure (network, 5xx, signed-URL expiry): exit 0
 *     (DON'T fail Hermes boot). Customer keeps minimal bootstrap from
 *     setup-script. bundle_pull_attempts row inserted with appropriate
 *     status. Next boot retries.
 *
 * Idempotent: each boot writes /var/lib/weuseai/bundle/<slug>/.installed-version
 * after a successful install. Subsequent boots compare desired vs
 * installed; skip pull if already at the right version.
 */

export type BundlePullScriptParams = {
  /**
   * Customer's UUID — written to .env at provision time, read by the
   * boot script via `source /home/weuseai/.hermes/.env`.
   */
  customerId: string
  /**
   * Bundle-fetch Edge Function URL. Defaults to production. Tests can
   * override to point at a mock server.
   */
  bundleFetchUrl?: string
  /**
   * Bundle-pull-record Edge Function URL. Defaults to production.
   */
  bundlePullRecordUrl?: string
}

const DEFAULT_BUNDLE_FETCH_URL =
  'https://gtjgsligllbjcisiyrah.supabase.co/functions/v1/bundle-fetch'
const DEFAULT_BUNDLE_PULL_RECORD_URL =
  'https://gtjgsligllbjcisiyrah.supabase.co/functions/v1/bundle-pull-record'

const BUNDLE_DIR_BASE = '/var/lib/weuseai/bundle'
const HERMES_SKILLS_DIR = '/home/weuseai/.hermes/skills'
const PULL_LOG = '/var/log/weuseai-bundle-pull.log'
const FETCH_TIMEOUT_SEC = 30
const DOWNLOAD_TIMEOUT_SEC = 60

/**
 * Generate the bash script. Writes to /usr/local/bin/weuseai-bundle-pull
 * during initial provisioning.
 *
 * `set -u` is on (catch unset env vars), but `set -e` is OFF — we want
 * graceful failure: any error inside the script logs + records telemetry
 * + exits 0 so Hermes can still boot with the minimal bootstrap.
 */
export function buildBundlePullScript(p: BundlePullScriptParams): string {
  const fetchUrl = p.bundleFetchUrl ?? DEFAULT_BUNDLE_FETCH_URL
  const recordUrl = p.bundlePullRecordUrl ?? DEFAULT_BUNDLE_PULL_RECORD_URL

  return `#!/bin/bash
# weuseai-bundle-pull — Phase 2E-2.
# Generated by services/provisioning/src/bundle-pull-script.ts.
# Do not edit on the VPS; re-provision to update.
#
# Runs as Hermes systemd ExecStartPre. Pulls the per-agent bundle from
# Storage and installs SKILL.md files into Hermes' discovery path.
# Failure mode: log + record + exit 0 (degraded mode over boot-failure).

set -u
set -o pipefail

LOG="${PULL_LOG}"
mkdir -p "$(dirname "$LOG")"
touch "$LOG"
chmod 0644 "$LOG"

log() {
  echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*" | tee -a "$LOG"
}

# ─── Read provisioning env ────────────────────────────────────────────
if [ ! -f /home/weuseai/.hermes/.env ]; then
  log "✗ /home/weuseai/.hermes/.env missing; cannot pull bundle"
  exit 0
fi
set -a
source /home/weuseai/.hermes/.env
set +a

CID="\${WEUSEAI_CUSTOMER_ID:-${p.customerId}}"
SLUG="\${WEUSEAI_AGENT_SLUG:-the-pro}"
TIER="\${WEUSEAI_TIER:-starter}"

if [ -z "$CID" ] || [ -z "$SLUG" ]; then
  log "✗ Missing WEUSEAI_CUSTOMER_ID or WEUSEAI_AGENT_SLUG in .env"
  exit 0
fi

# ─── Telemetry helper ─────────────────────────────────────────────────
record_attempt() {
  local status="$1"
  local version_requested="\${2:-}"
  local version_installed="\${3:-}"
  local error_detail="\${4:-}"
  local bytes_pulled="\${5:-}"
  local duration_ms="\${6:-}"

  local payload
  payload=$(cat <<JSON
{
  "customer_id": "$CID",
  "agent_slug": "$SLUG",
  "version_requested": "$version_requested",
  "version_installed": "$version_installed",
  "status": "$status",
  "error_detail": "$error_detail",
  "bytes_pulled": $\{bytes_pulled:-null\},
  "duration_ms": $\{duration_ms:-null\}
}
JSON
)
  # Best-effort POST. Any failure here is silently swallowed — telemetry
  # write must never propagate to customer-facing chat behavior.
  curl -fsS -X POST "${recordUrl}" \\
    -H "Content-Type: application/json" \\
    -d "$payload" \\
    --max-time 10 \\
    >> "$LOG" 2>&1 || log "⚠ telemetry record failed (non-fatal)"
}

START_MS=$(date +%s%3N)

# ─── Fetch metadata: which version + signed URL? ──────────────────────
log "Fetching bundle metadata for $SLUG (cid=$CID, tier=$TIER)"
RESPONSE=$(curl -fsS -X POST "${fetchUrl}" \\
  -H "Content-Type: application/json" \\
  -d "{\\"customer_id\\":\\"$CID\\",\\"agent_slug\\":\\"$SLUG\\"}" \\
  --max-time ${FETCH_TIMEOUT_SEC} 2>>"$LOG") || {
    DURATION=$(( $(date +%s%3N) - START_MS ))
    log "✗ bundle-fetch failed; customer keeps minimal bootstrap"
    record_attempt "storage_unavailable" "" "" "bundle-fetch HTTP failure" "" "$DURATION"
    exit 0
  }

# Lightweight JSON parse via grep + sed. Avoids requiring jq on the VPS.
# JSON shape from bundle-fetch:
#   { "version": "1.0.0", "signed_url": "https://...", "expires_at": "..." }
VERSION=$(echo "$RESPONSE" | grep -oE '"version":"[^"]+"' | head -n1 | sed 's/"version":"\\([^"]*\\)"/\\1/')
SIGNED_URL=$(echo "$RESPONSE" | grep -oE '"signed_url":"[^"]+"' | head -n1 | sed 's/"signed_url":"\\([^"]*\\)"/\\1/' | sed 's|\\\\/|/|g')

if [ -z "$VERSION" ] || [ -z "$SIGNED_URL" ]; then
  DURATION=$(( $(date +%s%3N) - START_MS ))
  log "✗ bundle-fetch returned malformed response: $RESPONSE"
  record_attempt "failed" "" "" "bundle-fetch malformed response" "" "$DURATION"
  exit 0
fi

# ─── Idempotency gate ─────────────────────────────────────────────────
INSTALLED_FILE="${BUNDLE_DIR_BASE}/$SLUG/.installed-version"
if [ -f "$INSTALLED_FILE" ]; then
  INSTALLED_VERSION=$(cat "$INSTALLED_FILE")
  if [ "$INSTALLED_VERSION" = "$VERSION" ]; then
    DURATION=$(( $(date +%s%3N) - START_MS ))
    log "✓ Bundle $SLUG@$VERSION already installed; re-applying tier filter only"
    apply_tier_filter "$SLUG" "$VERSION" "$TIER"
    record_attempt "success" "$VERSION" "$VERSION" "" "" "$DURATION"
    exit 0
  fi
  log "Installed version $INSTALLED_VERSION differs from target $VERSION; pulling fresh"
fi

# ─── Download + extract ──────────────────────────────────────────────
TARGET_DIR="${BUNDLE_DIR_BASE}/$SLUG/$VERSION"
mkdir -p "$TARGET_DIR"

log "Downloading $SLUG@$VERSION..."
TMPFILE=$(mktemp /tmp/weuseai-bundle.XXXXXX.tar.gz)
trap 'rm -f "$TMPFILE"' EXIT

curl -fsSL "$SIGNED_URL" -o "$TMPFILE" --max-time ${DOWNLOAD_TIMEOUT_SEC} 2>>"$LOG" || {
  DURATION=$(( $(date +%s%3N) - START_MS ))
  log "✗ Download failed"
  record_attempt "failed" "$VERSION" "" "download HTTP failure" "" "$DURATION"
  exit 0
}

BYTES=$(stat -c%s "$TMPFILE" 2>/dev/null || stat -f%z "$TMPFILE" 2>/dev/null || echo 0)
log "Downloaded $BYTES bytes"

tar -xzf "$TMPFILE" -C "$TARGET_DIR" 2>>"$LOG" || {
  DURATION=$(( $(date +%s%3N) - START_MS ))
  log "✗ Extract failed"
  record_attempt "failed" "$VERSION" "" "tar extract failure" "$BYTES" "$DURATION"
  exit 0
}

chown -R weuseai:weuseai "$TARGET_DIR"

# ─── Apply tier filter ────────────────────────────────────────────────
apply_tier_filter() {
  local slug="$1"
  local version="$2"
  local tier="$3"
  local manifest="${BUNDLE_DIR_BASE}/$slug/$version/manifest.json"

  if [ ! -f "$manifest" ]; then
    log "⚠ manifest.json missing in bundle ($manifest); skipping tier filter"
    return
  fi

  # For each skills/<id>/ directory in the bundle, decide install vs skip
  # by checking whether $tier is in the skill's enabled_for_tiers OR (legacy)
  # whether $tier is at-or-above the legacy tier value.
  #
  # No jq dependency: use Python (always available on Ubuntu base images)
  # for the JSON parse + tier filtering decision.
  python3 - "$manifest" "$tier" <<'PYEOF' > /tmp/weuseai-skill-filter.txt
import json, sys
manifest_path, tier = sys.argv[1], sys.argv[2]
with open(manifest_path) as f:
    m = json.load(f)
TIER_RANK = { 'starter': 1, 'pro': 2, 'studio': 3 }
def tier_to_efl(t):
    rank = TIER_RANK.get(t, 0)
    return [k for k, v in TIER_RANK.items() if v >= rank]
for skill in m.get('skills', []):
    sid = skill.get('id')
    if not sid:
        continue
    efl = skill.get('enabled_for_tiers')
    if not efl:
        legacy = skill.get('tier')
        if legacy:
            efl = tier_to_efl(legacy)
    if efl and tier in efl:
        print(f'INSTALL\\t{sid}')
    else:
        print(f'SKIP\\t{sid}\\t' + ','.join(efl or []))
PYEOF

  while IFS=$'\\t' read -r action skill_id rest; do
    case "$action" in
      INSTALL)
        local src="${BUNDLE_DIR_BASE}/$slug/$version/skills/$skill_id/SKILL.md"
        local dst="${HERMES_SKILLS_DIR}/$skill_id/SKILL.md"
        if [ -f "$src" ]; then
          mkdir -p "$(dirname "$dst")"
          cp "$src" "$dst"
          chown -R weuseai:weuseai "$(dirname "$dst")"
          log "  ✓ installed $skill_id"
        else
          log "  ⚠ $skill_id manifest entry exists but $src missing"
        fi
        ;;
      SKIP)
        # Remove the symlink/file if present (tier downgrade path).
        rm -f "${HERMES_SKILLS_DIR}/$skill_id/SKILL.md" 2>/dev/null
        log "  ✗ skipped $skill_id (tier=$tier not in [$rest])"
        ;;
    esac
  done < /tmp/weuseai-skill-filter.txt

  rm -f /tmp/weuseai-skill-filter.txt
}

apply_tier_filter "$SLUG" "$VERSION" "$TIER"

# ─── Mark installed ───────────────────────────────────────────────────
echo "$VERSION" > "$INSTALLED_FILE"

DURATION=$(( $(date +%s%3N) - START_MS ))
log "✓ Bundle install complete: $SLUG@$VERSION ($BYTES bytes, \${DURATION}ms)"
record_attempt "success" "$VERSION" "$VERSION" "" "$BYTES" "$DURATION"
exit 0
`
}
